owdb:
  image: postgres
  ports:
    - "5432"
owwebserver:
  build: .
  command: /bin/bash -l -c "find /home/ontoworks"
  volumes:
    - ~/dockermount:/home/ontoworks/webserver
  ports:
    - "3000:3000"
  links:
    - owdb
