#!/bin/bash

echo "Usage: railsStart [max [heap [min]]]"

if [ $# -eq 0 ]; then
  max="1024"
  heap="1024"
  min="512"
elif [ $# -eq 1 ]; then
  max="$1"
  heap="1024"
  min="512"
elif [ $# -eq 2 ]; then
  max="$1"
  heap="$2"
  min="512"
else
  max="$1"
  heap="$2"
  min="$3"
fi

echo "Running: jruby -J-Xmn${heap}m -J-Xms${min}m -J-Xmx${max}m -S rails s"

jruby -J-Xmn${heap}m -J-Xms${min}m -J-Xmx${max}m -S rails s
